import { Metadata } from "next";

export const metadata: Metadata = {
  title: "CytoGenesis Admin",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <section
      className="bg-gray-50
  "
    >
      {children}
    </section>
  );
}
