import { Metadata } from "next";
import dynamic from "next/dynamic";
import { userVisit } from "../services/userServices/userServices";

export const metadata: Metadata = {
  title: "CytoGenesis",
  description: "Generated by create next app",
};

const HeroMain = dynamic(() => import("./sections/Hero/HeroMain"));
const IntroMain = dynamic(() => import("./sections/introduction/IntroMain"));
const MissVision = dynamic(() => import("./sections/mission/MissVision"));
const About = dynamic(() => import("./sections/about/AboutMain"));
const Choose = dynamic(() => import("./sections/choose/ChooseMain"));
const Team = dynamic(() => import("./sections/team/TeamMain"));
const Partners = dynamic(() => import("./sections/partner/PartnerMain"));
const Career = dynamic(() => import("./sections/career/CareerMain"));
const Contact = dynamic(() => import("./sections/contact/ContactMain"));

export default async function Page() {
  try {
    await userVisit();
  } catch (error) {
    console.error("Error during call:", error);
  }
  return (
    <div className="overflow-clip">
      <HeroMain />
      <IntroMain />
      <MissVision />
      <About />
      <Choose />
      <Team />
      <Partners />
      <Career />
      <Contact />
    </div>
  );
}
