// import { Metadata } from "next";
// import dynamic from "next/dynamic";

// export const metadata: Metadata = {
//   title: "CytoGenesis",
//   description: "Generated by create next app",
// };
// const HeroMain = dynamic(() => import("./sections/Hero/HeroMain"));
// const IntroMain = dynamic(() => import("./sections/introduction/IntroMain"));
// const MissVision = dynamic(() => import("./sections/mission/MissVision"));
// const About = dynamic(() => import("./sections/about/AboutMain"));
// const Choose = dynamic(() => import("./sections/choose/ChooseMain"));
// const Team = dynamic(() => import("./sections/team/TeamMain"));
// const Partners = dynamic(() => import("./sections/partner/PartnerMain"));
// const Career = dynamic(() => import("./sections/career/CareerMain"));
// const Contact = dynamic(() => import("./sections/contact/ContactMain"));
// function page() {
//   return (
//     <div className="overflow-clip">
//       <HeroMain />
//       <IntroMain />
//       <MissVision />
//       <About />
//       <Choose />
//       <Team />
//       <Partners />
//       <Career />
//       <Contact />
//     </div>
//   );
// }

// export default page;

import axios from "axios";
import { Metadata } from "next";
import dynamic from "next/dynamic";
import { postRequest } from "../services/globalServices";
import { userVisit } from "../services/userServices/userServices";

export const metadata: Metadata = {
  title: "CytoGenesis",
  description: "Generated by create next app",
};

const HeroMain = dynamic(() => import("./sections/Hero/HeroMain"));
const IntroMain = dynamic(() => import("./sections/introduction/IntroMain"));
const MissVision = dynamic(() => import("./sections/mission/MissVision"));
const About = dynamic(() => import("./sections/about/AboutMain"));
const Choose = dynamic(() => import("./sections/choose/ChooseMain"));
const Team = dynamic(() => import("./sections/team/TeamMain"));
const Partners = dynamic(() => import("./sections/partner/PartnerMain"));
const Career = dynamic(() => import("./sections/career/CareerMain"));
const Contact = dynamic(() => import("./sections/contact/ContactMain"));

async function trackUserVisit() {
  try {
    await userVisit();
  } catch (error) {
    console.error("Error tracking user visit:", error);
  }
}

export default async function Page() {
  await trackUserVisit();

  return (
    <div className="overflow-clip">
      <HeroMain />
      <IntroMain />
      <MissVision />
      <About />
      <Choose />
      <Team />
      <Partners />
      <Career />
      <Contact />
    </div>
  );
}
